### ISSUE TITLE
Streamhub Video Plugin - Trending Movies doesn't work

### ISSUE THREAD

**Issue by iCanuck** [sClarkeIsBack/StreamHub#1]
Trending Movies doesn't work.

**Comment by Asc3nsi0n** [comment]
Seems to be lines#123+132 in the movies index. 
I cannot figure out the issue though.

**Comment by viewer777** [comment]
Use a trakt account and trending menu will work.

Asc3nsi0n its line#59 you can change to an IMDb address if you want. eg. http://www.imdb.com/search/title?title_type=trending,tv_movie

**Comment by sClarkeIsBack** [comment]
Fixed cheers guys
